const propertiesForRent = [
    {
        propertyId: 1,
        propertyName: 'Cozy Apartment',
        numberOfRooms: 2,
        price: 2000,
        location: 'Downtown',
        propertyType: 'Apartment',
        isFurnished: true,
        amenities: ['WiFi', 'Parking', 'Gym'],
        available: true,
        placesNearby: ['Coffee Shops', 'Grocery Store', 'Parks']
    },
    {
        propertyId: 2,
        propertyName: 'Spacious House',
        numberOfRooms: 4,
        price: 2500,
        location: 'Suburb',
        propertyType: 'House',
        isFurnished: false,
        amenities: ['Backyard', 'Garage'],
        available: false,
        placesNearby: ['Schools', 'Shopping Mall', 'Restaurants']
    },
    {
        propertyId: 3,
        propertyName: 'Modern Condo',
        numberOfRooms: 1,
        price: 900,
        location: 'City Center',
        propertyType: 'Condo',
        isFurnished: true,
        amenities: ['Security', 'Pool'],
        available: true,
        placesNearby: ['Public Transportation', 'Entertainment Venues', 'Cafes']
    },
    {
        propertyId: 4,
        propertyName: 'Luxury Penthouse',
        numberOfRooms: 3,
        price: 3500,
        location: 'City Center',
        propertyType: 'Penthouse',
        isFurnished: true,
        amenities: ['Private Terrace', 'Swimming Pool', 'Gourmet Kitchen'],
        available: true,
        placesNearby: ['Fine Dining Restaurants', 'Art Galleries', 'Theater']
    },
    {
        propertyId: 5,
        propertyName: 'Studio Loft',
        numberOfRooms: 1,
        price: 1100,
        location: 'Art District',
        propertyType: 'Studio',
        isFurnished: false,
        amenities: ['Exposed Brick Walls', 'Art Studio Space'],
        available: true,
        placesNearby: ['Art Studios', 'Cafes', 'Creative Workspaces']
    },
    {
        propertyId: 6,
        propertyName: 'Seaside Villa',
        numberOfRooms: 5,
        price: 5000,
        location: 'Beachfront',
        propertyType: 'Villa',
        isFurnished: true,
        amenities: ['Private Beach Access', 'Jacuzzi', 'Outdoor Barbecue'],
        available: true,
        placesNearby: ['Beach Clubs', 'Seafood Restaurants', 'Water Sports']
    },
    {
        propertyId: 7,
        propertyName: 'Mountain Retreat',
        numberOfRooms: 3,
        price: 1800,
        location: 'Mountain Range',
        propertyType: 'Cabin',
        isFurnished: true,
        amenities: ['Fireplace', 'Hiking Trails'],
        available: true,
        placesNearby: ['Ski Resorts', 'National Parks', 'Scenic Trails']
    },
    {
        propertyId: 8,
        propertyName: 'Urban Loft',
        numberOfRooms: 2,
        price: 1600,
        location: 'City Center',
        propertyType: 'Loft',
        isFurnished: true,
        amenities: ['Exposed Ductwork', 'City View'],
        available: true,
        placesNearby: ['Art Galleries', 'Nightlife', 'Dining']
    },
    {
        propertyId: 9,
        propertyName: 'Family Home',
        numberOfRooms: 4,
        price: 2200,
        location: 'Suburb',
        propertyType: 'House',
        isFurnished: false,
        amenities: ['Backyard', 'Playroom'],
        available: true,
        placesNearby: ['Parks', 'Schools', 'Community Centers']
    },
    {
        propertyId: 10,
        propertyName: 'Downtown Loft',
        numberOfRooms: 1,
        price: 1300,
        location: 'Downtown',
        propertyType: 'Loft',
        isFurnished: true,
        amenities: ['Rooftop Access', 'Modern Design'],
        available: false,
        placesNearby: ['Shopping', 'Cafes', 'Entertainment']
    },
    {
        propertyId: 11,
        propertyName: 'Charming Cottage',
        numberOfRooms: 2,
        price: 1500,
        location: 'Village',
        propertyType: 'Cottage',
        isFurnished: true,
        amenities: ['Garden', 'Fireplace'],
        available: true,
        placesNearby: ['Local Shops', 'Historic Sites', 'Walking Trails']
    },
    {
        propertyId: 12,
        propertyName: 'Rural Farmhouse',
        numberOfRooms: 3,
        price: 2000,
        location: 'Countryside',
        propertyType: 'Farmhouse',
        isFurnished: false,
        amenities: ['Large Garden', 'Farmland Views'],
        available: true,
        placesNearby: ['Farms', 'Nature Reserves', 'Quiet Retreats']
    },
    {
        propertyId: 13,
        propertyName: 'City View Apartment',
        numberOfRooms: 2,
        price: 1400,
        location: 'City Center',
        propertyType: 'Apartment',
        isFurnished: true,
        amenities: ['Balcony', 'Fitness Center'],
        available: true,
        placesNearby: ['Dining', 'Shopping', 'Public Transportation']
    },
    {
        propertyId: 14,
        propertyName: 'Lakefront Cabin',
        numberOfRooms: 2,
        price: 1700,
        location: 'Lakeside',
        propertyType: 'Cabin',
        isFurnished: false,
        amenities: ['Lake Access', 'Outdoor Fire Pit'],
        available: true,
        placesNearby: ['Fishing Spots', 'Boating Docks', 'Picnic Areas']
    },
    {
        propertyId: 15,
        propertyName: 'City Skyline Penthouse',
        numberOfRooms: 3,
        price: 4000,
        location: 'City Center',
        propertyType: 'Penthouse',
        isFurnished: true,
        amenities: ['Private Elevator', 'Skyline Views'],
        available: true,
        placesNearby: ['Luxury Shopping', 'Fine Dining', 'Theater']
    },
    {
        propertyId: 16,
        propertyName: 'Eco-Friendly Apartment',
        numberOfRooms: 2,
        price: 1300,
        location: 'Green Neighborhood',
        propertyType: 'Apartment',
        isFurnished: true,
        amenities: ['Solar Panels', 'Recycling Facilities'],
        available: true,
        placesNearby: ['Eco Markets', 'Parks', 'Sustainable Living']
    },
    {
        propertyId: 17,
        propertyName: 'Golf Course Villa',
        numberOfRooms: 4,
        price: 2800,
        location: 'Golf Community',
        propertyType:'Villa',
        isFurnished: true,
        amenities: ['Golf Course Access', 'Private Pool'],
        available: true,
        placesNearby: ['Golf Clubhouse', 'Walking Trails', 'Fine Dining']
    },
    {
        propertyId: 18,
        propertyName: 'Industrial Loft',
        numberOfRooms: 1,
        price: 1100,
        location: 'Warehouse District',
        propertyType: 'Loft',
        isFurnished: false,
        amenities: ['Exposed Brick', 'High Ceilings'],
        available: true,
        placesNearby: ['Art Galleries', 'Live Music Venues', 'Hip Cafes']
    },
    {
        propertyId: 19,
        propertyName: 'Historic Townhouse',
        numberOfRooms: 3,
        price: 1800,
        location: 'Historic District',
        propertyType: 'Townhouse',
        isFurnished: true,
        amenities: ['Original Features', 'Private Garden'],
        available: true,
        placesNearby: ['Museums', 'Antique Shops', 'Cultural Events']
    },
    {
        propertyId: 20,
        propertyName: 'Lakefront Retreat',
        numberOfRooms: 2,
        price: 1600,
        location: 'Lakefront',
        propertyType: 'Cottage',
        isFurnished: false,
        amenities: ['Lake Views', 'Boat Dock'],
        available: true,
        placesNearby: ['Nature Trails', 'Fishing Spots', 'Scenic Views']
    },
    
]

export default propertiesForRent

